### ISSUE TITLE
Average Call Duration, Stacked Bar Chart rendering Segment Order/Colours Inconsistently

### ISSUE THREAD

**Issue by johnM2401** [ivylabs/suitecrm-analytics#289] opened 2021-06-18 11:43 UTC
**Quick Note**
Quick Note after our call at Fri 18th Jun, 1pm
As we are toggling the "Stacked" option for these charts, this issue may no longer be viable.
(Will depend on how the Bars generate after stacking is disabled)

---------------

<br>

**Describe the bug**
On the Average Call Duration report, the Stacked Bar Chart appears to render inconsistently, depending on the Date Parameters used.

It appears as though the 3 Segments can render in a different order, with what seems to be no consistency/pattern

I understand why this is occurring, as the order appears to be dependant on the returned Data.
However, after discussing with Ross/Evan, we agreed it would be good if this was consistent, if possible, for user experience.

See screenshots for examples.

<br>

**Component
What component does this bug relate to?
1. Report - Average Call Duration

<br>

**Solution File
AverageCallDuration.prpt

<br>

**To Reproduce**
1. Contain Data in the CRM for this report. (ie, Calls against Leads/Opportunity/Cases), with one of these having notably more time allocated
2. Pull this into the DWH via the ./run script
3. Navigate to the Average Call Duration report
4. Set the Date Parameters to contain the Calls that you created
5. View the Stacked Bar chart's segments, and the order they are in
6. Change the Date Parameters, ensuring the date range still contains your items
7. The order of the Stacked Bar chart segments appear to change, which might be confusing to users

<br>

**Expected behavior**
The Same order/Colours are associated to the Segments/Modules, on the Stacked Bar

<br>

**Screenshots**
ie, If I do March-March, with my Dataset:
![image](https://user-images.githubusercontent.com/13675281/122555256-f78b2b80-d031-11eb-9bad-1acb0e0339bc.png)

The Largest segment, (Leads), is in the centre.

However, if I change the Date Parameters to March-May, the Largest Segment, (Leads), is at the bottom
(Both Segments are associated to Leads)
![image](https://user-images.githubusercontent.com/13675281/122555331-125da000-d032-11eb-96e6-e3c6237a8b84.png)

And If I choose March-July, the Largest Segment, (Leads), is at the top:
![image](https://user-images.githubusercontent.com/13675281/122555469-3f11b780-d032-11eb-95ee-a17001fd897e.png)

While not a major functionality issue, I feel the inconsistency may be misleading/confusing to some users.

<br>

**Desktop (please complete the following information):**
-    OS: Ubuntu 18.04
  -  Browser: Firefox 88.01

**Comment by harrisward** [comment] 2021-06-21 08:44
@johnM2401 Added an order by clause to keep the database sorted correctly and set the bar / line chart to stacked = false based on Fridays discussion.

**Comment by harrisward** [comment] 2021-06-21 08:45
Feature Branch: https://github.com/ivylabs/suitecrm-analytics/tree/feature-289
Pull Request: https://github.com/ivylabs/suitecrm-analytics/pull/290

**Comment by johnM2401** [comment] 2021-06-21 13:19
Hey @harrisward, 

Like #286, Wasn't sure if you wanted me to take a look at this separate from the Master branch, but I have had a look.
Looks much better, able to differentiate the chart bars much easier.

However, one minor point of Feedback I have is that the Order of the bars does not match the Order of the columns

![image](https://user-images.githubusercontent.com/13675281/122767820-f14bb800-d29a-11eb-9b67-a8b7564196fd.png)

ie, 
The Chart bars are ordered:  Leads - Opportunities - Cases
Whereas the Report tables are ordered: Leads - Cases - Opportunities

I think it would be worth making these two match, for easier readability for users.

What are your thoughts?

**Comment by harrisward** [comment] 2021-06-21 14:20
@johnM2401 I've reorder the columns to Cases, Leads and Opportunities.

Merged the code to the master branch

**Closed as completed by harrisward** 2021-06-21 14:20 UTC
Labels: bug

**Comment by johnM2401** [comment] 2021-06-22 09:03
Hey @harrisward 

Pulled latest master.
The Bars do seem to be ordered differently, but don't seem to be Cases->Leads->Opportunities

They now appear to be 
Opportunities->Cases->Leads

![image](https://user-images.githubusercontent.com/13675281/122896376-ec414400-d340-11eb-86d2-7b62804694f0.png)

**Comment by harrisward** [comment] 2021-06-22 09:11
Can you make sure you have refreshed everything? When I build from master I get the following:

![image](https://user-images.githubusercontent.com/6827832/122897700-c2d0ea00-d339-11eb-8f9f-81e08eda138e.png)

**Comment by johnM2401** [comment] 2021-06-22 09:34
Hey @harrisward 

So, I do see that order when using Demo Data:
![image](https://user-images.githubusercontent.com/13675281/122901217-3fb59100-d345-11eb-8b9e-cf6f5397f356.png)


However, the order appears to be different using Live Data:
![image](https://user-images.githubusercontent.com/13675281/122901383-65db3100-d345-11eb-9c54-f8cb44fb6461.png)

**Comment by harrisward** [comment] 2021-06-25 06:35
Hi @johnM2401 I've tried everything I can to recreate the issue my side including manually forcing the chart data but I can't reproduce the issue you are seeing. Im sure you have already tried but my only suggestion is to rebuild the whole server to make sure no caching exists anywhere. The latest output I get is in the screenshot below:

![image](https://user-images.githubusercontent.com/6827832/123380844-7840af00-d57f-11eb-871e-49b18686cfe1.png)

Because of this im going to put this ticket into backlog and take it out of the 1.4 release

**Comment by johnM2401** [comment] 2021-06-25 08:11
Hey @harrisward 

hmmmm
I typically rebuild the full server whenever I pull down from master, so it should be fairly cache-free

However, it seems like the chart may be cached to some extent in your screenshot? 
(Unless i've misread it?)


When I have the parameters:
Call Period From: 2021-07
Call Period To: 2021-07

This is all I see:
![image](https://user-images.githubusercontent.com/13675281/123392267-c2805b00-d594-11eb-87d2-b6f8b0ae6b28.png)


I don't believe I have *any* Call Data from 2019, as these are the options I have for parameters:
![image](https://user-images.githubusercontent.com/13675281/123392431-f3609000-d594-11eb-94d3-85340e7428e9.png)
Where it looks like your chart is displaying a bunch of data from 2019


<br>

But, to confirm, this is what I see after a full re-build:

![image](https://user-images.githubusercontent.com/13675281/123392573-1b4ff380-d595-11eb-8d9c-eca6ddd84bc3.png)

**Comment by harrisward** [comment] 2021-06-25 08:21
@johnM2401 Thats okay its not cached. The data in the chart is not related to any real or demo data. Its is a dummy dataset to test the output of the chart if certain data is sent to it. I recreated the same structure as your dataset and got the results you see before.

As this is aesthetic im not too worried for fixing it in this release
